name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build


      # Run Tests Build
    - name: Run gradle tests
      run: ./gradlew test

      # Run Build Project
    - name: Build gradle project
      run: ./gradlew build
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Develop Branch
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git checkout -b develop
          git push origin develop